create accomodation section
JoannaTabbi/TabbiJoanna_2_30102021 pull request #19
Opened 2021-11-17 19:09 UTC by JoannaTabbi

Close #7

2021-11-17 21:55 UTC, Tutt-J requested changes

2021-11-17 21:55 UTC, Tutt-J commented on index.html
> +        <h4><a href="#">Afficher plus</a></h4>
This is not a title

2021-11-18 22:45 UTC, Tutt-J approved these changes

2021-11-19 08:28 UTC, JoannaTabbi commented on index.html
> +        <h4><a href="#">Afficher plus</a></h4>
<h4> removed

2021-11-19 08:28 UTC, merged